exports.getJobCard = [{
    job_id : 2134,
    job_name : "assistant professor",
    salary: "50000",
    experience_required : "5+year",
    mode : "fullTime",
    eligibility : "PHd",
    description : "Website is a hyper-media information storage system linking resources around the world. In website, browsers allow highlighted words or an icon which is called hyper links to display text, video, graphics and sound on a local computer screen",
    tech : true,
},
{
    job_id : 2174,
    job_name : "Non Tech assistant professor",
    salary: "50000",
    experience_required : "5+year",
    mode : "fullTime",
    eligibility : "PHd",
    description : "Website is a hyper-media information storage system linking resources around the world. In website, browsers allow highlighted words or an icon which is called hyper links to display text, video, graphics and sound on a local computer screen",
    tech : false,
},
{
    job_id : 2174,
    job_name : "Non Tech assistant professor",
    salary: "50000",
    experience_required : "5+year",
    mode : "fullTime",
    eligibility : "PHd",
    description : "Website is a hyper-media information storage system linking resources around the world. In website, browsers allow highlighted words or an icon which is called hyper links to display text, video, graphics and sound on a local computer screen",
    tech : false,
}
]